openapi: 3.0.0
info:
  title: AROSAJE API
  description: An API for data of Arosaje Application
  version: 1.0.0

servers:
  - url: http://localhost:4000/api

paths:
  /announces:
    get:
      tags: [Announces]
      summary: Get all announces
      description: Returns a list of all announces
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Announce'
        '500':
          description: Failed to get announces

    post:
      tags: [Announces]
      summary: Create a new announce
      description: Creates a new announce and returns it
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Announce'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announce'
        '400':
          description: Failed to create announce

  /announces/{id}:
    get:
      tags: [Announces]
      summary: Get announce by ID
      description: Returns the announce with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the announce to retrieve
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announce'
        '404':
          description: Announce not found
        '500':
          description: Failed to get announce

    put:
      tags: [Announces]
      summary: Update announce
      description: Updates the announce with the specified ID and returns it
      parameters:
        - name: id
          in: path
          description: ID of the announce to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Announce'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announce'
        '404':
          description: Announce not found
        '400':
          description: Failed to update announce

    delete:
      tags: [Announces]
      summary: Delete announce
      description: Deletes the announce with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the announce to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Announce deleted successfully'
        '404':
          description: Announce not found
        '500':
          description: Failed to delete announce

components:
  schemas:
    Announce:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          readOnly: true
          example: 1
        ANNOUNCER_ID:
          type: integer
          format: int64
          example: 1
        UPKEEP_ID:
          type: integer
          format: int64
          example: 1
        TITLE:
          type: string
          example: "New Maintenance Schedule"
        BODY:
          type: string
          example: "Details about the new maintenance schedule."
        START_DATE:
          type: string
          format: date
          example: "2023-06-01"
        END_DATE:
          type: string
          format: date
          example: "2023-06-30"
        CREATED_AT:
          type: string
          format: date-time
          example: "2023-05-25T10:30:00Z"
        UPDATED_AT:
          type: string
          format: date-time
          example: "2023-05-25T10:45:00Z"
      required:
        - ANNOUNCER_ID
        - UPKEEP_ID
        - TITLE
        - BODY
        - START_DATE
        - END_DATE
