openapi: 3.0.3
info:
  title: Arosaje API
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/auth

tags:
  - name: Authentication
    description: User authentication

paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      summary: Sign up a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: User registered successfully
  /auth/signin:
    post:
      tags:
        - Authentication
      summary: Sign in an existing user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthenticationResponseDto'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
                example: Invalid credentials
components:
  schemas:
    AuthenticationResponseDto:
      type: object
      properties:
        jwt:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.FGK5PCL49k3jfNCq6wZtn6T-uG9Dv4hOYIm55xTux8w"
        message:
          type: string
          example: User logged in successfully
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        email:
          type: string
          example: "torek@example.com"
        password:
          type: string
          example: 5f4dcc3b5aa765d61d8327deb882cf99
        username:
          type: string
          example: "Torek"
        firstName:
          type: string
          example: "Tom"
        lastName:
          type: string
          example: "Zarek"
        streetNumber:
          type: string
          example: 5
        streetName:
          type: string
          example: "Rue de la Paix"
        zipCode:
          type: string
          example: "75000"
        city:
          type: string
          example: "Paris"
        country:
          type: string
          example: "France"
        birthDate:
          type: string
          example: "1980-01-01"
        lastGpsLocation:
          type: string
          example: "48.8566,2.3522"
        lastGpsLocationDate:
          type: string
          example: "2021-01-01T00:00:00.000Z"
        lastLoginDate:
          type: string
          example : "2021-01-01T00:00:00.000Z"
        roleId:
          type: integer
          example: 1
        createdAt:
          type: string
          example: "2021-01-01T00:00:00.000Z"
        updatedAt:
          type: string
          example: "2021-01-01T00:00:00.000Z"
  
