openapi: 3.0.0
info:
  title: AROSAJE API
  description: An API for data of Arosaje Application
  version: 1.0.0

servers:
  - url: http://localhost:4000/api

paths:
  /conversations:
    post:
      tags: [Conversation]
      summary: Create a new conversation
      description: Creates a new conversation and returns it
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conversation'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '400':
          description: Failed to create conversation

    get:
      tags: [Conversation]
      summary: Get all conversations
      description: Returns a list of all conversations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '500':
          description: Failed to get conversations

  /conversations/{id}:
    get:
      tags: [Conversation]
      summary: Get conversation by ID
      description: Returns the conversation with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the conversation to retrieve
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
        '500':
          description: Failed to get conversation

    put:
      tags: [Conversation]
      summary: Update conversation
      description: Updates the conversation with the specified ID and returns it
      parameters:
        - name: id
          in: path
          description: ID of the conversation to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conversation'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Conversation not found
        '400':
          description: Failed to update conversation

    delete:
      tags: [Conversation]
      summary: Delete conversation
      description: Deletes the conversation with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the conversation to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Conversation not found
        '400':
          description: Failed to delete conversation

components:
  schemas:
    Conversation:
      type: object
      properties:
        USER_ID1:
          type: integer
          format: int64
          example: 1
        USER_ID2:
          type: integer
          format: int64
          example: 2
      required:
        - USER_ID1
        - USER_ID2
