openapi: 3.0.0
info:
  title: Arosaje API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/conversation-participants

tags:
    - name: ConversationParticipant

paths:
  /conversation-participants:
    get:
      tags:
        - ConversationParticipant
      summary: Get all conversation participants
      description: Returns a list of all conversation participants
      responses:
        '200':
          description: List of conversation participants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConversationParticipant'
        '500':
            description: Internal server error
    post:
      tags:
        - ConversationParticipant
      summary: Create a conversation participant
      description: Creates a new conversation participant
      requestBody:
        description: The participant to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationParticipant'
      responses:
        '201':
          description: The created conversation participant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationParticipant'
        '500':
          description: Internal server error

  /conversation-participants/{id}:
    get:
      tags:
        - ConversationParticipant
      summary: Get a conversation participant by ID
      description: Returns a single conversation participant by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
              application/json:
                schema:
                    $ref: '#/components/schemas/ConversationParticipant'
        '500':
          description: Internal server error

    put:
      tags:
        - ConversationParticipant
      summary: Update a conversation participant
      description: Updates an existing conversation participant
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: The updated participant
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversationParticipant'
      responses:
        '200':
          description: The updated conversation participant
          content:
              application/json:
                schema:
                    $ref: '#/components/schemas/ConversationParticipant'
        '404':
          description: Participant not found
        '500':
          description: Internal server error

    delete:
      tags:
          - ConversationParticipant
      summary: Delete a conversation participant
      description: Deletes a conversation participant by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: OK
        '404':
          description: Participant not found
        '500':
          description: Internal server error

components:
  schemas:
    ConversationParticipant:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        conversation_id:
          type: integer
        user_id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - name
        - email

