openapi: 3.0.0
info:
  title: AROSAJE API
  description: An API for data of Arosaje Application
  version: 1.0.0

servers:
  - url: http://localhost:4000/api

paths:
  /medias:
    post:
      tags: [Media]
      summary: Create a new media
      description: Creates a new media and returns it
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Media'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '500':
          description: Failed to create media

    get:
      tags: [Media]
      summary: Get all media
      description: Returns a list of all media
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Media'
        '500':
          description: Failed to get media

  /medias/{id}:
    get:
      tags: [Media]
      summary: Get media by ID
      description: Returns the media with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the media to retrieve
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '404':
          description: Media not found
        '500':
          description: Failed to get media

    put:
      tags: [Media]
      summary: Update media
      description: Updates the media with the specified ID and returns it
      parameters:
        - name: id
          in: path
          description: ID of the media to update
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Media'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Media'
        '404':
          description: Media not found
        '500':
          description: Failed to update media

    delete:
      tags: [Media]
      summary: Delete media
      description: Deletes the media with the specified ID
      parameters:
        - name: id
          in: path
          description: ID of the media to delete
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Media deleted successfully'
        '404':
          description: Media not found
        '500':
          description: Failed to delete media

components:
  schemas:
    Media:
      type: object
      properties:
        ID:
          type: integer
          format: int64
          readOnly: true
          example: 1
        USER_ID:
          type: integer
          format: int64
          example: 1
        TYPE:
          type: string
          example: "image"
        FORMAT:
          type: string
          example: "jpeg"
        ORIGINAL_NAME:
          type: string
          example: "photo.jpg"
        HASHED_NAME:
          type: string
          example: "a1b2c3d4e5f6.jpg"
        CREATED_AT:
          type: string
          format: date-time
          example: "2023-05-25T10:30:00Z"
        UPDATED_AT:
          type: string
          format: date-time
          example: "2023-05-25T10:45:00Z"
      required:
        - USER_ID
        - TYPE
        - FORMAT
        - ORIGINAL_NAME
        - HASHED_NAME
