openapi: 3.0.0
info:
  title: Arosaje API
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/plants

paths:
  /plants:
    post:
      summary: Create a new plant
      tags: [Plant]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
        '500':
          description: Failed to create plant

    get:
      summary: Get all plants
      tags: [Plant]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
        '500':
          description: Failed to get plants

  /plants/{id}:
    get:
      summary: Get a plant by ID
      tags: [Plant]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
        '404':
          description: Plant not found
        '500':
          description: Failed to get plant

    put:
      summary: Update a plant
      tags: [Plant]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Plant'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
        '404':
          description: Plant not found
        '500':
          description: Failed to update plant

    delete:
      summary: Delete a plant
      tags: [Plant]
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: Plant deleted successfully
        '404':
          description: Plant not found
        '500':
          description: Failed to delete plant

components:
  schemas:
    Plant:
      type: object
      properties:
        ID:
          type: integer
          readOnly: true
        OWNER_ID:
          type: integer
        SPECIES_ID:
          type: integer
        CREATED_AT:
          type: string
          format: date
          readOnly: true
        UPDATED_AT:
          type: string
          format: date
          readOnly: true
      required:
        - OWNER_ID
        - SPECIES_ID