openapi: 3.0.0
info:
  title: AROSAJE API
  description: An API for data of Arosaje Application
  version: 1.0.0

servers:
  - url: http://localhost:4000/api

tags:
  - name: Species
    description: API endpoints for managing species

paths:
  /species:
    post:
      tags: [Species]
      summary: Create a new species
      requestBody:
        description: The species to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Species'
      responses:
        '201':
          description: The created species
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'
        '500':
          description: Internal server error

    get:
      tags: [Species]
      summary: Get all species
      description: Returns a list of all species
      responses:
        '200':
          description: List of species
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Species'
        '500':
          description: Internal server error

  /species/{id}:
    get:
      tags: [Species]
      summary: Get a species by ID
      description: Returns a single species by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'
        '404':
          description: Species not found
        '500':
          description: Internal server error

    put:
      tags: [Species]
      summary: Update a species
      description: Updates an existing species
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: The updated species
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Species'
      responses:
        '200':
          description: The updated species
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Species'
        '404':
          description: Species not found
        '500':
          description: Internal server error

    delete:
      tags: [Species]
      summary: Delete a species
      description: Deletes a species by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: OK
        '404':
          description: Species not found
        '500':
          description: Internal server error

components:
  schemas:
    Species:
      type: object
      properties:
        ID:
          type: integer
          readOnly: true
        NAME:
          type: string
